# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscstatapp', '0036_remove_tkgthresholds_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholds',
            name='percentage_reduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='\u043f\u0440\u043e\u0446\u0435\u043d\u0442 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u043f\u043e\u0440\u043e\u0433\u0430'),
        ),
        migrations.AddField(
            model_name='thresholds',
            name='value_lower',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='\u0430\u0432\u0430\u0440\u0438\u0439\u043d\u044b\u0439 \u043f\u043e\u0440\u043e\u0433 \u043f\u0440\u0438 \u0441\u043d\u0438\u0436\u0435\u043d\u0438\u0438 \u0441\u043e\u0431\u044b\u0442\u0438\u0439'),
        ),
    ]
